name: Premium-Filestore

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure environment
        env:
          API_HASH: ${{ secrets.API_HASH }}
          API_ID: ${{ secrets.API_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
        run: |
          echo "BOT_TOKEN=$BOT_TOKEN" >> $GITHUB_ENV
          echo "API_ID=$API_ID" >> $GITHUB_ENV
          echo "API_HASH=$API_HASH" >> $GITHUB_ENV
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV

      

      - name: Run Premium-Filestore
        run: python3 bot.py

